# deploy_docker_container.yml
- name: Deploy Docker container
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Pull and run NGINX container (пример)
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        ports:
          - "80:80"
