---
- name: Установка и настройка Nginx на Ubuntu
  hosts: webservers
  become: true

  tasks:
    - name: Установка Nginx
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Убедиться, что Nginx запущен
      service:
        name: nginx
        state: started
        enabled: true

    - name: Копирование кастомной конфигурации (если есть)
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
        backup: true
      notify: Перезапустить Nginx
      when: nginx_custom_config is defined and nginx_custom_config

  handlers:
    - name: Перезапустить Nginx
      service:
        name: nginx
        state: restarted
